sudo: false
language: java
jdk:
  - oraclejdk7

notifications:
  email:
    on_success: change
    on_failure: change

after_success: 
  - ./gradlew uploadArchives -Pusername=$BINTRAY_USERNAME -Ppassword=$BINTRAY_API_KEY
