sudo: false
language: java
jdk:
  - oraclejdk7

notifications:
  email:
    on_success: change
    on_failure: change

after_success: 
  - ./gradlew uploadArchives -PbintrayUsername=$BINTRAY_USERNAME -PbintrayPassword=$BINTRAY_API_KEY
